### ISSUE TITLE
모든 페이지에서 GET genres 요청 계속 반복

### ISSUE THREAD

**Issue by eunhabaek** [LV-3/FE#148]
- Nav bar가 있는 모든 페이지에서 GET genres 요청이 여러번 수행 됨
- Redux 사용 가능하다면 Nav bar를 활용해도 될 듯

**Comment by kangansoo** [comment]
네브바의 장르 데이터들은 네브바 최초 진입 시 데이터를 불러오고 리덕스에 저장 후 새로고침 방지를 위하여 로컬스토리지에도 저장
