### ISSUE TITLE
응답없음 페이지...

### ISSUE THREAD

**Issue by kangansoo** [LV-3/FE#271]
- 클릭했을 때 클릭한 페이지에 접속하고 난 후 에러를 감지해서 noResponse 페이지로 가기 때문에 navigate(-1) 눌러도 의미가 없음 → navigate(-2)는 안 됨
    ex) 메인에서 디테일을 눌렀을 때 디테일에서 에러가 뜬다면 접속 과정이 메인 → 디테일(에러 감지) → noResponse 페이지 (여기서 뒤로가기 해봐야 디테일인데 계속 에러인 상태)

얘기해봐야 함

- [x] 일단 로그인 페이지 ("/") 로 이동하도록 변경

**Comment by eunhabaek** [comment]
- 로그인 페이지 ("/") 로 이동하도록 변경
